version: '3.4'  
  
services:
  elasticsearch:  
   container_name: elasticsearch  
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1  
   ports:  
    - 9200:9200  
   volumes:  
    - elasticsearch-data:/usr/share/elasticsearch/data  
   environment:  
    - xpack.monitoring.enabled=true  
    - xpack.watcher.enabled=false  
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  
    - discovery.type=single-node  
   networks:  
    - infra-net  
  
  kibana:  
   container_name: kibana  
   image: docker.elastic.co/kibana/kibana:7.9.1  
   ports:  
    - 5601:5601  
   depends_on:  
    - elasticsearch
   environment:  
    - ELASTICSEARCH_URL=http://localhost:9200  
   networks:  
    - infra-net

  sftp:
    image: atmoz/sftp
    container_name: taskmanager.sftp
    ports:
        - "2222:22"
    command: binh:pass:1001
    volumes:
        - D:\sftp-upload:/home/binh/upload
    networks:
      - infra-net

  mssql:
    container_name: taskmanager.sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest+
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Thistimeisover1!"
    ports:
      - 5433:1433
    networks:
      - infra-net
networks:  
  infra-net:  
    driver: bridge  
  
volumes:  
  elasticsearch-data: