version: '3.4'

services:
  taskmanager.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    container_name: taskmanager.api
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - taskmanager-net
  sftp:
    image: atmoz/sftp
    container_name: taskmanager.sftp
    ports:
        - "2222:22"
    command: binh:pass:1001
    volumes:
        - D:\sftp-upload:/home/binh/upload
    networks:
      - taskmanager-net
  # mssql:
  #   container_name: taskmanager.sql-server
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   restart: always
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     SA_PASSWORD: "Thistimeisover1!"
  #   ports:
  #     - 5433:1433
  #   networks:
  #     - taskmanager-net
  frontend:
    container_name: taskmanager.front-end
    build: ./front-end/TaskManager
    volumes:
      - './front-end/TaskManager/:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - taskmanager-net
networks:
  taskmanager-net:
    driver: bridge
    ipam:
      driver: default