version: '3.4'

services:
  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManager.API/Dockerfile
    container_name: taskmanager.api
    ports:
      - "8080:80"
    networks:
      - taskmanager-net
networks:
  taskmanager-net:
    driver: bridge