global using Mapster;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using MimeKit;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Data;
global using System.Data.Common;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq.Dynamic.Core;
global using System.Linq.Expressions;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using TaskManager.Core.Core;
global using TaskManager.Core.DTOs;
global using TaskManager.Core.Entities;
global using TaskManager.Core.Helper;
global using TaskManager.Core.ViewModel;
global using static TaskManager.Core.Extensions.CoreExtensions;
global using Version = TaskManager.Core.Entities.Version;